import { Component } from '@angular/core';
import { Property } from '../../../core/interfaces/property.interface';
import { FormsModule } from '@angular/forms';  // <-- Import this
import { PropertyService } from '../../../core/service/property/property.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-property-add',
  imports: [FormsModule,],
  templateUrl: './property-add.component.html',
  styleUrl: './property-add.component.css'
})
export class PropertyAddComponent {
  
  
  property: Property = { // Initialize as 0 or leave it out if generated by the backend
    id: 0,
    name: '',
    line_1: '',
    line_2: '',
    province: '',
    country: '',
    postal_code: '',
    type: 'apartment', // default value
    status: 'available', // default value
    updated_at: '',
    created_at: ''
  };

  constructor(private propertyService: PropertyService, private router: Router) {}  

  onSubmit() {
    console.log('Submitted property:', this.property);
  
    this.propertyService.addProperty(this.property).subscribe(
      response => {
        console.log('Property added:', response);
        this.router.navigate(['/admin/properties']);
      },
      error => {
        if (error.status === 422) {
          console.error('Validation error:', error.error); // Log validation errors
          // Display error messages to the user
        
        } else {
          console.error('Error adding property:', error);
          // Handle other errors (e.g., network issues, server errors)
        }
      }
    );

  }

}
